### PR TITLE
Users on channel

### PR DESCRIPTION
**Pull request by sevcik-martin**

### CODE REVIEW

**Comment by domhanak** [comment]
Status? Feel free to include fixes for state from MS2

**Comment by domhanak** [comment]
Status? @Sevitas

**Comment by sevcik-martin** [comment]
working on redux changes from ms2, rewriting almost all channel functionality

**Comment by domhanak** [comment]
Okey-dokey juet remove the label when done :)

**Review by domhanak — APPROVED** [review]

**Pull request merged**
